### ISSUE TITLE
AddHttpMessageHandler not honored while using with .net framework application

### ISSUE THREAD

**Issue by noufionline** [KevinDockx/HttpClientInNetCore#1]
Hi Kevin,

I am trying to use IHttpClientFactory in my WPF Prism Application. Since I cannot use the Microsoft Dependency Injection container in Prism I have used Unity Provider to convert my registration to Unity like below.

```csharp
  var unityContainer = containerRegistry.GetContainer();

            ServiceCollection serviceCollection = new ServiceCollection();

       
            serviceCollection.AddHttpClient();

            serviceCollection.AddHttpClient<IRepositoryBase,RepositoryBase>()
                .AddHttpMessageHandler<RefreshTokenHandler>()
                .ConfigurePrimaryHttpMessageHandler(handler =>
                new HttpClientHandler()
                {
                    AutomaticDecompression = System.Net.DecompressionMethods.GZip
                });

           
           
            serviceCollection.BuildServiceProvider(unityContainer);
``` 

```csharp

   public class RefreshTokenHandler:DelegatingHandler
    {
        private readonly IApiTokenProvider _tokenProvider;

        public RefreshTokenHandler(IApiTokenProvider tokenProvider)
        {
            _tokenProvider = tokenProvider;
        }

        public RefreshTokenHandler(HttpMessageHandler innerHandler, IApiTokenProvider tokenProvider) : base(
            innerHandler)
        {
            _tokenProvider = tokenProvider;
        }
        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var token = await _tokenProvider.GetTokenAsync();
            request.Headers.Authorization=new AuthenticationHeaderValue("Bearer",token);
            return await base.SendAsync(request, cancellationToken);
        }

        
    }
```

Any thoughts?

**Comment by noufionline** [comment]
The Issue is resolved. Thanks

**Comment by ch4m0n1x101** [comment]
@noufionline I'm trying to do the same. Did you get this working? I'm trying to use HttpClientFactory with Prism, Refit, Fusillade and Polly.

**Comment by noufionline** [comment]
@ledragon101 yes. Today is holiday in this part of the world. I will share the code once I am in the office

**Comment by ch4m0n1x101** [comment]
@noufionline Great thanks! I'll look forward to it...enjoy your holiday ;-)

**Comment by jthegeman** [comment]
@noufionline what did you do to solve this?

**Comment by noufionline** [comment]
@jthegeman if you are using Unity as your container then the code I gave on top is enough to register HttpClientFactory with the Microsoft Container then using the Unit Extension method load all the registrations to Prism Unity container.

**Comment by noufionline** [comment]
> @ledragon101 yes. Today is holiday in this part of the world. I will share the code once I am in the office 

Sorry brother. I completely missed you. Did you get the solution ? If you need any help I am more that happy to help

**Comment by jthegeman** [comment]
@noufionline I am using DryIoc, so should it be almost the same implementation, just with DryIoc.

**Comment by noufionline** [comment]
Yes I guess. They must be having a similar extension method for this as well. Since the new container abstraction you can convert to unity with few lines of code anyway!
